#!/usr/local/bin/gawk -f

@include "../lib/utils.awk" ;

BEGIN{

  # READ QUERY STRING
  split(ENVIRON["QUERY_STRING"], query, "&");
  for (i1 in query)
	{
	  split(query[i1], tmpq, "=");
	  f[tmpq[1]] = urldecode(tmpq[2]); 
	}

   RS="\x04" ;

   "curl -L http://insidewood.lib.ncsu.edu/search" | getline spage ;

   n = split(spage,sl,"\n");
   for (i = 1; i < n; i++)
	 {
	   if (sl[i] ~ "keywordsearchform")
		 {
		   split(sl[i], sm, "\"");
		 }
	 }

   # "curl -L -d keywordSearch=Acer \"http://insidewood.lib.ncsu.edu/" sm[6] "\"" | getline spage2 ;
   # print "Content-type: text/html\n\n" spage2 ;

   # cookie = sm[6] ;
   # gsub(/;jsessionid=/,"",cookie);
   # gsub(/\?wicket.*/,"",cookie);
   # print "Set-Cookie: JSESSIONID=" cookie "; Path=/" ;

   print "Content-type: text/html\n\n<html><head> \
          </head> \
	      <body> \
            <p>Redirecting to Insidewood query on " f["genus"] "</p> \
            <p>(If this link does not work, please clear your cookie \
               for insidewood.lib.ncsu.edu)</p> \
          <script type=\"text/javascript\"> \
             /* document.cookie = \"JSESSIONID=" cookie "; Path=/\" ; */ \
             var form = document.createElement(\"form\"); \
             form.setAttribute(\"method\", \"post\"); \
             form.setAttribute(\"action\", \
                  \"http://insidewood.lib.ncsu.edu/" sm[6] "\"); \
             var kw = document.createElement(\"input\"); \
             kw.setAttribute(\"type\", \"hidden\"); \
             kw.setAttribute(\"name\", \"keywordSearch\"); \
             kw.setAttribute(\"value\", \"" f["genus"] "\"); \
             form.appendChild(kw); \
             document.body.appendChild(form); \
             form.submit(); \
          </script></body></html>" ;

   # See: http://stackoverflow.com/questions/133925/javascript-post-request-like-a-form-submit

   exit;

}